version: '2'
services:
  newoapp13-app:
    image: newoapp13
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp13-postgresql:5432/NewoApp13
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://newoapp13-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://newoapp13-elasticsearch:9200
    ports:
      - 8080:8080
  newoapp13-postgresql:
    extends:
      file: postgresql.yml
      service: newoapp13-postgresql
  newoapp13-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: newoapp13-elasticsearch
